import fs from 'fs-extra';
import * as path from 'path';
import { ProjectConfig } from '../types/index.js';

export async function generateLambdaSam(projectPath: string, config: ProjectConfig, ext: string) {
  if (config.framework !== 'express') {
    return;
  }

  const isTS = ext === 'ts';
  const lambdaContent = isTS
    ? `import serverless from 'serverless-http';
import { createApp } from './app.js';
import logger from './utils/logger.js';

const lambdaHandler = serverless(createApp());

export const handler = async (event: any, context: any) => {
  context.callbackWaitsForEmptyEventLoop = false;

  try {
    return await lambdaHandler(event, context);
  } catch (error) {
    logger.error('Lambda request failed.', {
      error: error instanceof Error ? error.message : String(error),
      ...(error instanceof Error && error.stack ? { stack: error.stack } : {}),
    });
    throw error;
  }
};
`
    : `import serverless from 'serverless-http';
import { createApp } from './app.js';
import logger from './utils/logger.js';

const lambdaHandler = serverless(createApp());

export const handler = async (event, context) => {
  context.callbackWaitsForEmptyEventLoop = false;

  try {
    return await lambdaHandler(event, context);
  } catch (error) {
    logger.error('Lambda request failed.', {
      error: error instanceof Error ? error.message : String(error),
      ...(error instanceof Error && error.stack ? { stack: error.stack } : {}),
    });
    throw error;
  }
};
`;

  const template = {
    AWSTemplateFormatVersion: '2010-09-09',
    Transform: 'AWS::Serverless-2016-10-31',
    Description: `${config.name} generated by nod-cli`,
    Globals: {
      Function: {
        Runtime: 'nodejs20.x',
        Timeout: 30,
        MemorySize: 512,
        Environment: {
          Variables: {
            NODE_ENV: 'production',
          },
        },
      },
    },
    Resources: {
      ApiFunction: {
        Type: 'AWS::Serverless::Function',
        Properties: {
          Handler: 'dist/lambda.handler',
          CodeUri: '.',
          Events: {
            HttpApi: {
              Type: 'HttpApi',
              Properties: {
                Path: '/{proxy+}',
                Method: 'ANY',
              },
            },
          },
        },
      },
    },
    Outputs: {
      ApiUrl: {
        Description: 'HTTP API endpoint',
        Value: {
          'Fn::Sub': 'https://${ServerlessHttpApi}.execute-api.${AWS::Region}.amazonaws.com',
        },
      },
    },
  };

  await fs.outputFile(path.join(projectPath, `src/lambda.${ext}`), lambdaContent);
  await fs.outputFile(path.join(projectPath, 'template.yaml'), toYaml(template));
  await fs.outputFile(path.join(projectPath, 'samconfig.toml'), `version = 0.1

[default.global.parameters]
stack_name = "${config.name}"

[default.build.parameters]
cached = true
parallel = true

[default.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
resolve_s3 = true
`);
}

function toYaml(value: any, indent = 0): string {
  const pad = ' '.repeat(indent);

  if (Array.isArray(value)) {
    return value
      .map(item => `${pad}- ${isScalar(item) ? formatScalar(item) : `\n${toYaml(item, indent + 2)}`}`)
      .join('\n');
  }

  if (value && typeof value === 'object') {
    return Object.entries(value)
      .map(([key, item]) => {
        if (isScalar(item)) {
          return `${pad}${key}: ${formatScalar(item)}`;
        }
        return `${pad}${key}:\n${toYaml(item, indent + 2)}`;
      })
      .join('\n');
  }

  return `${pad}${formatScalar(value)}`;
}

function isScalar(value: any): boolean {
  return value === null || ['string', 'number', 'boolean'].includes(typeof value);
}

function formatScalar(value: any): string {
  if (value === null) return 'null';
  if (typeof value === 'number' || typeof value === 'boolean') return String(value);
  if (value === '') return '""';
  if (/^[A-Za-z0-9_./{}:+-]+$/.test(value)) return value;
  return JSON.stringify(value);
}
